### ISSUE TITLE
JEE7-Demo in Jenkins

### ISSUE THREAD

**Issue by Clasino** [hostettler/JEE7-Demo#4]
@mencattini, @hostettler, @stklik

So I've created a pipeline in jenkins with JEE7-Demo following https://jenkins.io/doc/tutorials/build-a-java-app-with-maven/ (I've added the Jenkinsfile).
[Jenkinsfile.txt](https://github.com/hostettler/JEE7-Demo/files/1879038/Jenkinsfile.txt)

The Build and the Containers stages work. But the Test stage give this:
[ErrorReport.txt](https://github.com/hostettler/JEE7-Demo/files/1879044/ErrorReport.txt)

However this does not happend when running localy.

I've also modified other things:

- [pom.xml](https://github.com/hostettler/JEE7-Demo/pom.xml): changing the scope of log4j-slf4j-impl, log4j-api, log4j-core in the dependency to test;

- [StudentServiceRs.java](https://github.com/hostettler/JEE7-Demo/jee7-students-service/src/main/java/ch/demo/business/service/StudentServiceRs.java): adding "@Consumes({ "application/json" })" to POST and PUT and also inverted them;

- [PhoneNumber.java](https://github.com/hostettler/JEE7-Demo/jee7-students-service/src/main/java/ch/demo/dom/PhoneNumber.java): add "public PhoneNumber(){}";

**Comment by hostettler** [comment]
Still having the problem?

**Comment by Clasino** [comment]
Yes

**Comment by stklik** [comment]
Trying to reproduce but I'm running into different issues.

About the errors:
The exception says that it cannot connect to `localhost:9990`.
I wonder whether Jenkins kills the docker images from the **Containers** stage before running the **Test** stage.

Another possible issue: are the containers from the **Containers** stage exporting the ports? (`-p 9990:9990`)

However, I don't have experience with `Jenkinsfile`.

**Comment by Clasino** [comment]
About the errors:

- When I do a `docker ps` on the server after launching a Jenkins build, they are still there:
```
[10/04/18 15:53:15 cotte4@pinfo2:~]$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                                                               NAMES
cae7bfa8eea2        jee7-test-wildfly     "/opt/jboss/wildfl..."   38 seconds ago      Up 36 seconds       0.0.0.0:8787->8787/tcp, 0.0.0.0:9990->9990/tcp, 9090/tcp, 0.0.0.0:18080->8080/tcp   unruffled_kare
84ac19321a4a        jee7-demo-mysql       "docker-entrypoint..."   39 seconds ago      Up 38 seconds       0.0.0.0:13306->3306/tcp                                                             dazzling_goldstine
ee3fbca26c6d        jenkinsci/blueocean   "/sbin/tini -- /us..."   2 minutes ago       Up 2 minutes        0.0.0.0:8080->8080/tcp, 50000/tcp                                                   laughing_curran
```

- About exporting the port 9990, the `jee7-test-wildfly` has the port 9990 open and we can connect to it through a browser. We also tried to put `args '-p 9990:9990'` in the docker agent but it creates a conflict. We can also access the DB through SQuirreL.

**Comment by stklik** [comment]
One more possibility that just came to my mind:

Since you're running the tests inside a docker container, it might be that `localhost` points to the test-container itself, rather than to the host machine (whose port is mapped to 9990).

Can you try adding `--net="host"` to the run command of the test container? [1]
This will assert that `localhost` points to the host machine, instead of the container itself.

[1] More info in the docker documentation or [here](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)

**Comment by kaikoveritch** [comment]
I'll let our sys-admin handle that additional test, but I would say it seems unlikely, given that we were able to access the wildfly page with a browser (meaning that it is up, running and indeed accessible through the port).

**Comment by stklik** [comment]
You were able to access from the host machine, not from via the test
container, if I understood correctly.

Hence the net config to assert that the container looks like the host...

**Comment by kaikoveritch** [comment]
Indeed... I have just understood what you meant. That will indeed be interesting to check.
We will keep you updated.

**Comment by Clasino** [comment]
Finally it works. Thanks
